name: Health Check

on:
  schedule: 
    - cron: '45 * * * *'

jobs:
  steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.5
      with:
        url: https://pokedexfso.herokuapp.com/health